# Generated by Django 3.2.5 on 2021-07-25 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('self_auth', '0002_remove_profile_date_joined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Censorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TotalTheme',
            fields=[
                ('slug', models.SlugField(max_length=250, primary_key=True, serialize=False, verbose_name='Слаг')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование общей темы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TalkTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Наименование')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('busy', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('total_theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total', to='chat.totaltheme')),
                ('users', models.ManyToManyField(related_name='participants', to='self_auth.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Текст')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='author', to='self_auth.profile')),
                ('sending', models.ManyToManyField(related_name='send_to', to='chat.TalkTheme')),
            ],
        ),
    ]
