# Generated by Django 3.2.5 on 2021-07-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='totaltheme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='total-theme'),
        ),
    ]
