# Generated by Django 3.2.5 on 2021-07-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('self_auth', '0003_auto_20210726_1616'),
        ('chat', '0002_totaltheme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talktheme',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='participants', to='self_auth.Profile'),
        ),
    ]
