# Generated by Django 3.2.5 on 2021-07-27 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_talktheme_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sending',
            field=models.ManyToManyField(blank=True, related_name='send_to', to='chat.TalkTheme'),
        ),
    ]
