# Generated by Django 3.2.5 on 2021-07-27 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_message_sending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sending',
            field=models.ManyToManyField(blank=True, related_name='messages', to='chat.TalkTheme'),
        ),
    ]
