# Generated by Django 3.2.5 on 2021-07-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('self_auth', '0003_auto_20210726_1616'),
        ('chat', '0005_alter_message_sending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talktheme',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='users', to='self_auth.profile'),
        ),
    ]
